spring.application.name=User_Service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/Zaminex_UserService
spring.datasource.username=root
spring.datasource.password=Rupeshsql@7
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true

jwt.secretKey = 09er4fui487ttr9j439bu4itg438fno3je4bvk34g02f2